### PR TITLE
Fix some memory leaks in NotyfyObject.close()

### PR DESCRIPTION
**Pull request by rosenfeld**
I'm fixing some memory leaks in my application and some of them result from this plugin. Luckily this one was easy to fix. Now I'm going to investigate the causes for the jQRangeSlider plugin...

Without this patch it is easy to notice that some NotyfyObject's containers are still present under 'body' after close() is called. Only the li was being removed, not its ul container. There were also some other memory leaks which I believe should be all fixed now since the memory stopped growing up after creating and closing notifications...

### CODE REVIEW

**Comment by rosenfeld** [comment]
Actually, there are still remaining leaks... :( I'm currently investigating them...

**Comment by rosenfeld** [comment]
Ok, now I believe we should be all set (hopefully)

**Comment by Craga89** [comment]
Thanks @rosenfield!

**Comment by rosenfeld** [comment]
No problem :)
Em 18/04/2013 10:49, "Craig Michael Thompson" notifications@github.com
escreveu:

**Pull request merged**
